### ISSUE TITLE
Upgrade `actions-riff-raff` to v4

### ISSUE THREAD

**Issue by cemms1** [guardian/fonts#27]
This is a breaking change and will require a roleArn field to be provided to the GH action.
There's an example PR of the upgrade here: https://github.com/guardian/service-catalogue/pull/794

**Comment by akash1810** [comment]
Looks like v2 is currently in use, so this upgrade will include 2 major version bumps:
- v2 -> v3 is documented here https://github.com/guardian/actions-riff-raff/releases/tag/v3.0.0
- v3 -> v4 is documented here https://github.com/guardian/actions-riff-raff?tab=readme-ov-file#migrating-from-v3-to-v4

(We didn't standardise on a location...)

**Comment by sndrs** [comment]
thanks @akash1810 – @cemms1 i can take a look at this if you like?

**Comment by abeddow91** [comment]
@sndrs Oops, I missed this chat and made the changes here https://github.com/guardian/fonts/pull/29 -  if you're happy, I'll merge it in

**Comment by sndrs** [comment]
> @sndrs Oops, I missed this chat and made the changes here #29 - if you're happy, I'll merge it in

yeh delighted!
